# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.cache/wt [current_project]
set_property parent.project_path C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.srcs/sources_1/imports/VHD_files/inverter.vhd
  C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.srcs/sources_1/imports/VHD_files/mux16to1.vhd
  C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.srcs/sources_1/imports/VHD_files/config_RO.vhd
  C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.srcs/sources_1/imports/VHD_files/counter32bit.vhd
  C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.srcs/sources_1/imports/VHD_files/CRO_PUF.vhd
  C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.srcs/sources_1/imports/VHD_files/CRO_PUF_TOP.vhd
}
read_xdc C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.srcs/constrs_1/imports/CRO/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/patty/Documents/classes/ece559/git/HWSec_Project/16_CROs/16_CROs.srcs/constrs_1/imports/CRO/Nexys4_Master.xdc]

catch { write_hwdef -file CRO_PUF_TOP.hwdef }
synth_design -top CRO_PUF_TOP -part xc7a100tcsg324-1
write_checkpoint -noxdef CRO_PUF_TOP.dcp
catch { report_utilization -file CRO_PUF_TOP_utilization_synth.rpt -pb CRO_PUF_TOP_utilization_synth.pb }
